// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBDRQn6FZW31nFaljPDISolisJ0XULtlg',
    appId: '1:260056965360:android:150ecb7e11a85a84e82235',
    messagingSenderId: '260056965360',
    projectId: 'lebontemperament-c6af6',
    storageBucket: 'lebontemperament-c6af6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpMuGnxk92wvOjJ8UPYBzYNA7S8p5eCMw',
    appId: '1:260056965360:ios:ff6d60026bccf3a7e82235',
    messagingSenderId: '260056965360',
    projectId: 'lebontemperament-c6af6',
    storageBucket: 'lebontemperament-c6af6.firebasestorage.app',
    iosBundleId: 'com.lebontemperament.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpMuGnxk92wvOjJ8UPYBzYNA7S8p5eCMw',
    appId: '1:260056965360:ios:ff6d60026bccf3a7e82235',
    messagingSenderId: '260056965360',
    projectId: 'lebontemperament-c6af6',
    storageBucket: 'lebontemperament-c6af6.firebasestorage.app',
    iosBundleId: 'com.lebontemperament.app',
  );
}
